### ISSUE TITLE
Invalid date part value is reset to '0'

### ISSUE THREAD

**Issue by MattOz-CDS** [localgovdrupal/localgov_forms#13]
If a date part fails validation the data inputed is changed to 0. In my opinion this is not desirable.

When using the LocalGov Forms Date, what I've found is that if client-side validation is disabled on a webform and a user enters text into any of the date parts, when the form is submitted and passes through the various date validation methods, the value entered is changed into a '0'. 

When stepping through the code I found that this setting to '0' was happening on line 250 of the [Datelist.php](https://git.drupalcode.org/project/drupal/-/blob/9.3.x/core/lib/Drupal/Core/Datetime/Element/Datelist.php#L250) class in core. The reason I disabled client-side validation was because it was recommended to do so for the GDS date pattern. 

What we would like to happen is for the value **NOT** to be changed into a '0', but to remain as the value that was originally input e.g 'xx'.  We feel that this would provide a better user experience, and that a user should be able to correct what was entered in the date part.

Our objective is to find a way in which we can keep the erroneous value in situ. Below are screenshots showing what is currently happening. Please share your thoughts on this issue. 

**Before validation**
<img width="438" alt="Screenshot 2021-11-30 at 14 15 20" src="https://user-images.githubusercontent.com/88331824/144066018-9ac6c575-c45d-4e21-9bf8-54d45316dd40.png">

**After Validation**
<img width="527" alt="Screenshot 2021-11-30 at 14 15 33" src="https://user-images.githubusercontent.com/88331824/144064185-bbabbfd7-724a-4569-82ae-f0a646186cb6.png">

**Comment by andybroomfield** [comment]
@weebud did we solve this at BHCC?

**Comment by ekes** [comment]
Looking at it briefly that my temptation would be to add a earlier validator that maybe might even try and convert the string to the appropriate value; or set an error before it gets to the core validator.
