### ISSUE TITLE
Address lookup Webform element

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_forms#3]
Turn the existing [BHCC](https://www.brighton-hove.gov.uk) address lookup element into a generic one that can be powered by a variety of address lookup APIs.  Andy Broomfield of BHCC has kindly provided us with the BHCC address lookup code which forms the basis for this task.

@andrew-wallis @andybroomfield @tom-steel @richardaclarke @willguv

**Comment by richardaclarke** [comment]
Is there a standard for how an address lookup should function? If not, do we need to define this, so that we can have a standard API and make it easier for councils to plug in their own lookup?

My **assumption** would be that we would use addresses in the BS7666 standard as that's what's used by the LLPG. 

There is some guidance here but it doesn't cover the back-end API: https://design-system.service.gov.uk/patterns/addresses/

**Comment by andybroomfield** [comment]
I'm going to recommend that we actully get these to use the geocoder module, that way anything that needs to use address lookup can just plugin an off the shelf one they already have, or quickly code up a geocoder plugin if they need a custom one.

The current version of this at BHCC calls Central Hub directly, however we do now have this servce exposed as Geocoder plugins its just this element doesn't yet use them. This also means it would'nt involve councils having to make api changes to their back end systems, just build the appropriate geocoder or use the one bundled with Open Street Map.

**Comment by tom-steel** [comment]
> I'm going to recommend that we actully get these to use the geocoder module, that way anything that needs to use address lookup can just plugin an off the shelf one they already have, or quickly code up a geocoder plugin if they need a custom one.
> 
> The current version of this at BHCC calls Central Hub directly, however we do now have this servce exposed as Geocoder plugins its just this element doesn't yet use them. This also means it would'nt involve councils having to make api changes to their back end systems, just build the appropriate geocoder or use the one bundled with Open Street Map.

That looks like a slightly similar approach to the date picker - using an existing element but hacking it to present (or in this case get) data in a more useful way. Gets my vote.

Lets treat the current dev work as a MVP for using a different lookup service, and record this for future iterations.

**Comment by Adnan-cds** [comment]
Latest: I have added the [relevant files into the localgov_forms](https://github.com/localgovdrupal/localgov_forms/pull/6) module from a code archive that @andybroomfield  slacked me earlier.  I have also written some code to use Geocoder plugins as address lookup backends.  One or more plugins can now be selected when configuring the Address look Webform element.  Remaining tasks:
- Replace references to "bhcc_" with "localgov_forms_" in the source code.
- Add automated tests.

Very much work in progress.

@andrew-wallis @andybroomfield @tom-steel @richardaclarke @MattOz-CDS @willguv @finnlewis

**Comment by finnlewis** [comment]
@Adnan-cds : @ekes has written some geo lookup for the directories / venues / localgov_geo - worth making sure we're all in line here? https://github.com/localgovdrupal/localgov_geo

**Comment by ekes** [comment]
One thing that occurs to me as important if folk are using the OS Places API is that it can also be plugged into the Address Field autocompletion, and geocoding - and anywhere else we're doing geocoding. This can be done by writing a plugin for https://geocoder-php.org/ (and the Drupal module that wraps that https://drupal.org/project/gecoder ). I think there's quite a few additional features for the OS Places API, there's nothing stopping a plugin having extension methods for these, if you look at the examples there are several that do.

I'm not sure what the Webform address field is like, more basic than the addressfield module one I think. So I'm not sure how much of the javascript will be useful, but for 'address field' the code is https://github.com/localgovdrupal/localgov_geo/blob/1.x/modules/localgov_geo_address/src/Plugin/Field/FieldWidget/AutocompleteAddress.php and the slightly funky js https://github.com/localgovdrupal/localgov_geo/blob/1.x/modules/localgov_geo_address/js/autocomplete.js

Finally on the localgov_geo side, it does have the possibility to store things like an ID for locations, so it would be good to look at getting that in the geocode process if something like OS Places API is providing it.

**Comment by Adnan-cds** [comment]
> This can be done by writing a plugin for https://geocoder-php.org/

Yeah, that's the plan.  Andy has already written [two such plugins for the BHCC address lookup api](https://github.com/localgovdrupal/localgov_forms/tree/feature/address-lookup/modules/bhcc_central_hub/src/Geocoder/Provider) which is what I am currently using for testing.  I need to write one more such plugin for the [Ordnance Survey places API](https://apidocs.os.uk/docs/os-places-technical-detail#service-checks) and then we should be ready to roll.

**Comment by ekes** [comment]
> > This can be done by writing a plugin for https://geocoder-php.org/
> 
> Yeah, that's the plan. Andy has already written [two such plugins for the BHCC address lookup api](https://github.com/localgovdrupal/localgov_forms/tree/feature/address-lookup/modules/bhcc_central_hub/src/Geocoder/Provider) which is what I am currently using for testing. I need to write one more such plugin for the [Ordnance Survey places API](https://apidocs.os.uk/docs/os-places-technical-detail#service-checks) and then we should be ready to roll.

Cool. I certainly think the OS Places implementation is worth spinning out into a separate geocoder-php plugin (drupal independent composer install) and a gecoder plugin (in a module or submitted as a patch to the existing). Seems like something else other projects could use too?

**Comment by andybroomfield** [comment]
One thing I will say is we will most likly need to split out the central hub geocoder plugin as its only really useful if you are looking for addresses in Brighton and Hove, I inlcluded them as examples, though they are really internal API (fine for testing though).

**Comment by Adnan-cds** [comment]
> I certainly think the OS Places implementation is worth spinning out into a separate geocoder-php plugin.

Yeah, that's also part of the plan.  Good that we are all in agreement :)
