### ISSUE TITLE
Provide a local filter for LGD address lookup in Drupal forms

### ISSUE THREAD

**Issue by DavidBAsch** [localgovdrupal/localgov_forms#45]
**As a content designer** building Drupal forms containing the LGD address module
**I need to** be able to restrict the returned results on a street lookup to a local area
**So that** information isn't omitted where there are numerous streets of the same name across the country

Currently the address lookup module returns results from the whole country when using the street name as the criteria. The results are limited to 100 addresses, so it often doesn't return information for the related area (Croydon in this instance).

Although the postcode will return the correct area, in some instances, this might not be known; for example, if it's for reporting a pothole.

Having an option to restrict to a particular area would resolve this.

In this example, entering Sandown Road only returns Portsmouth addresses.

![image](https://github.com/localgovdrupal/localgov_forms/assets/14923610/e6aaf604-cf58-48a4-ae8e-4ff197093f27)

**Comment by Adnan-cds** [comment]
- [ ] Add option for adding a [Local custodian code](https://www.ordnancesurvey.co.uk/documents/product-support/support/abcore-gss-codes.csv)
- [ ] When available, apply the LOCAL_CUSTODIAN_CODE parameter to [address lookup calls](https://osdatahub.os.uk/docs/places/technicalSpecification).
