### ISSUE TITLE
Low-code platform integration

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_forms#50]
### Problem
The *Netcall Liberty Create* Low-code platform's [REST API](https://en.wikipedia.org/wiki/REST) can accept data from external systems.  This happens over [HTTP POST](https://en.wikipedia.org/wiki/POST_(HTTP)) requests.  The Drupal [Webform module](https://www.drupal.org/project/webform) already comes with a handler that can pass on form submission data to any REST API endpoint including Liberty Create's.  But if the API call fails for some reason, e.g. due to target platform downtime, there is no provision for retry.

### Solution
The [webform_queued_post_handler](https://packagist.org/packages/cyberwoven/webform_queued_post_handler) Drupal module extends the existing Drupal [Webform code](https://git.drupalcode.org/project/webform/-/blob/6.1.x/src/Plugin/WebformHandler/RemotePostWebformHandler.php?ref_type=heads) so that form submissions destined for the API call are saved in a [queue](https://en.wikipedia.org/wiki/Message_queue) rather than immediately acted upon.  This means the API call is made later.  But even this module [lacks](https://bitbucket.org/cyberwoven/webform_queued_post_handler/src/master/README.md#markdown-header-retries) the functionality to retry failed API calls.  To address this, we have raised a [pull request](https://bitbucket.org/cyberwoven/webform_queued_post_handler/pull-requests/1) that adds this retry-upon-failure functionality.

### What's next
- We have to wait until the pull request is accepted and a new release is made.
- More testing.

### Relevant links
- [Drupal module](https://packagist.org/packages/cyberwoven/webform_queued_post_handler) to enqueue HTTP POST requests born out of Drupal Webform submissions.
- Pull request in [Bitbucket](https://bitbucket.org/cyberwoven/webform_queued_post_handler/pull-requests/1).  This change extends the functionality of the above module so that failed API calls are retried later.  This is useful for surviving Low-code platform downtimes.
- [Liberty Create integration](https://www.netcall.com/platform/low-code/integration/).

Copying @willguv @finnlewis @ekes @andybroomfield  @MattOz-CDS

**Comment by finnlewis** [comment]
Discussing in Merge Monday.... @Adnan-cds points out that the configuration needed will depend on the webform in question and target API.

So how to provide this as default configuration?

I was wondering if an example module might be useful, including a default webform and configuration to post to a given Netcall API. We could then add video and docs to this.

**Comment by willguv** [comment]
Hi @Adnan-cds any update on this? Thanks

**Comment by Adnan-cds** [comment]
Update summary:
- The coding part of the work is complete.  Some of the code is in a custom module.  I am hoping to bring these to localgov_forms next week.  I will bring in some code and a sample Webform that shows how Editors should configure the integration.
- The [pull request](https://bitbucket.org/cyberwoven/webform_queued_post_handler/pull-requests/1) for fail-safe API integration is still pending.

**Comment by Adnan-cds** [comment]
[Ready for review](https://github.com/localgovdrupal/localgov_forms/pull/60) and testing.
