### ISSUE TITLE
Improvement to LGD forms address lookup validation.

### ISSUE THREAD

**Issue by DavidBAsch** [localgovdrupal/localgov_forms#55]
Currently there is no way to make the LGD address lookup mandatory because each block has the required setting but they are not independent of one another. This means there's potentially more work for back-office staff because they would need to contact the user to get the address if it wasn't entered.

Is there a possibility of building in a better validation model?

**Comment by DavidBAsch** [comment]
Update: it seems that there's been an update and it's now working as expected, so this can probably be closed.

**Comment by Adnan-cds** [comment]
Closing, as suggested above :)
