### ISSUE TITLE
[Feature] Display the Title of the Address lookup element by default

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_forms#64]
The [default configuration](https://git.drupalcode.org/project/webform/-/blob/6.2.x/src/Plugin/WebformElement/WebformCompositeBase.php?ref_type=heads#L78) of all Webform composite elements including our Address lookup element says that the title of the element should remain invisible by default.  While this configuration is easily changeable, for better UX, we would like it to be visible by default.

Copying @DavidBAsch @andybroomfield @finnlewis

**Comment by DavidBAsch** [comment]
Thanks @Adnan-cds, this is much better. It would be of interest to know why this element had the legend set to invisible by default.
