### ISSUE TITLE
Fix static analysis checks

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_forms#87]
See https://github.com/localgovdrupal/localgov_forms/actions/runs/10370984772/job/28710272432?pr=86#step:5:22

**Comment by millnut** [comment]
Started to work on some of the errors here https://github.com/localgovdrupal/localgov_forms/pull/89

**Comment by millnut** [comment]
All errors should now be fixed, the workflow is showing green for the PR above
