### ISSUE TITLE
[Address lookup] "Can't find the address?" button is always visible

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_forms#9]
Rich has pointed out that the "Can't find the addres?" button is visible even before any address searches have been performed.  Screenshot attached:
![screenshot-address-lookup-webform-element](https://user-images.githubusercontent.com/50206849/137727347-fff61b4d-609c-4989-87d4-77555e48c68e.png).

Perhaps it would be better if it appears after an **unsuccessful** search.  I am happy to implement the change.  But thought it better to consult first.  So, is this going to be acceptable with you @andrew-wallis @andybroomfield 

@richardaclarke @tom-steel

**Comment by andybroomfield** [comment]
Can't find address is to open up the manual address form, so maybe relabel, but it feels like it kinda needs to be present at all times.
Eg. Have lots of address forms on site, but know the address is often not in search, so direct to manual address.

**Comment by richardaclarke** [comment]
Where an address exists in a gazetteer, we shouldn't let user enter it manually because it will not have uprn and they might introduce typos. If the data is never integrated it might not matter.
I feel the manual address should only be available after a failed address lookup.

**Comment by tom-steel** [comment]
I would also vote for not showing it until someone can't look up their address - the value created by getting accurate and consistent address data is too great.

**Comment by richardaclarke** [comment]
Additionally, in the case of a 'not found' local address, it would be great to inform the land and property team so they can check the gazetteer. Sometimes addresses are missing for valid reasons, eg landlord has split a property but not informed the council.
But now I am being greedy - back-end notification for a future iteration. Although - it could be inferred from data.

**Comment by tom-steel** [comment]
We've been review some form design patterns across platforms in Croydon, [this is the current design](https://lbc-app-w-localgov-corpwebsite-p.azurewebsites.net/design-and-content-guidelines/components/forms/addresses) that we want to recreate in forms as much as possible, based heavily on the [GDS pattern](https://design-system.service.gov.uk/patterns/addresses/).
